Repository sparcs-kaist/taxi-back, pull requests merged in 2022-05, with the labels that each got.

#46 #44 add issue and PR template
  .github/ISSUE_TEMPLATE/bug-report-template.md
  .github/ISSUE_TEMPLATE/issue-template.md
  .github/pull_request_template.md
Labels: documentation

#49 Add prettier config
  .prettierignore
  .prettierrc.json
Labels: enhancement

#60 Add new profile images
  public/profile-images/default/CatGeoul.png
  public/profile-images/default/CatGreen.png
  public/profile-images/default/CatJabo.png
  public/profile-images/default/CatOTL.png
  public/profile-images/default/CatTaxi.png
  public/profile-images/default/GooseGeoul.png
  public/profile-images/default/GooseGreen.png
  public/profile-images/default/GooseJabo.png
  public/profile-images/default/GooseOTL.png
  public/profile-images/default/GooseTaxi.png
  public/profile-images/default/NupjukGeoul.png
  public/profile-images/default/NupjukGreen.png
  public/profile-images/default/NupjukJabo.png
  public/profile-images/default/NupjukOTL.png
  public/profile-images/default/NupjukTaxi.png
  public/profile-images/default/sample.png
Labels: enhancement, static router

#40 #39 simplify rooms api
  src/route/docs/rooms.md
  src/route/rooms.js
Labels: ⚒ enhancement, users router

#31 #25 rewrite join disconnect socket events
  app.js
  package.json
  src/auth/login.js
  src/db/mongo.js
  src/modules/socket.js
  src/route/chats.js
  src/route/chats.socket.js
  src/route/docs/chats.md
  src/route/rooms.js
  src/route/static.js
Labels: ⚒ enhancement, chatting

#57 #55 implement admin page
  .gitignore
  app.js
  package.json
  src/db/mongo.js
  src/middleware/adminAuth.js
  src/route/admin.js
Labels: ⚒ enhancement

#65 #64 remove module
  src/modules/chunkArray.js
  src/route/rooms.js
  src/taxiResponse.js
Labels: ⚒ enhancement
