Repository sparcs-kaist/taxi-back, pull requests merged in 2022-08, with the labels that each got.

#80 #76 manage error logging
  .gitignore
  app.js
  ecosystem.config.js
  package.json
  src/auth/login.js
  src/db/mongo.js
  src/middleware/auth.js
  src/modules/logAPIAccess.js
  src/modules/logger.js
  src/service/auth.replace.js
  src/service/rooms.js
  src/service/users.js
Labels: ⚒ enhancement

#83 #77 session 저장 방법 Redis-store로 변경
  .env.example
  app.js
  ecosystem.config.js
  package.json
  security.js
  src/middleware/session.js
  src/route/auth.js
  src/service/auth.js
Labels: ⚒ enhancement, authentication

#88 Fix: Set NODE_ENV for test
  package.json
Labels: 😱bug, testcase

#82 #69 채팅에서 이미지 전송
  src/db/mongo.js
  src/db/patterns.js
  src/route/chats.js
  src/route/chats.socket.js
  src/route/rooms.js
  src/service/chats.js
  src/service/logininfo.js
  src/service/rooms.js
Labels: chatting, 🖥 working

#96 #95 bug chat in msg not generated for creator
  src/db/mongo.js
  src/route/admin.js
  src/route/chats.socket.js
  src/route/docs/chats.md
  src/service/rooms.js
Labels: 😱bug, chatting

#94 #93 add ci
  .github/workflows/node.js.yml
  .gitignore
  package-lock.json
  package.json
  src/db/mongo.js
Labels: testcase

#98 #97 [Bug] Additional properties of "chatAfter" are not set properly
  src/service/chats.js
Labels: 😱bug, chatting

#79 #74 Validate from/to locations
  app.js
  src/db/mongo.js
  src/db/patterns.js
  src/route/docs/README.md
  src/route/docs/locations.md
  src/route/docs/rooms.md
  src/route/locations.js
  src/route/rooms.js
  src/service/locations.js
  src/service/rooms.js
Labels: rooms router, d-done

#105 Add: set default timezone to Seoul
  nodemon.json
  package.json
Labels: ⚒ enhancement

#110 Fix: 24시간 후 계산하는 방식 변경
  src/service/rooms.v2.js
Labels: 😱bug

#90 Create testcases for /json/logininfo
  .eslintrc.js
  package-lock.json
  package.json
  src/middleware/setTimestamp.js
  src/route/auth.js
  src/route/rooms.js
  src/service/auth.js
  src/service/auth.replace.js
  src/service/rooms.js
  test/auth.replace.js
  test/logininfo.js
Labels: authentication, testcase

#100 Add: support maxPartLength in /rooms/search
  src/route/docs/rooms.md
  src/route/docs/rooms.v2.md
  src/route/rooms.js
  src/route/rooms.v2.js
  src/service/rooms.js
  src/service/rooms.v2.js
Labels: ⚒ enhancement, rooms router

#108 #107 Update /rooms & /chats API to support chatting
  package-lock.json
  package.json
  security.js
  src/auth/login.js
  src/db/mongo.js
  src/modules/logger.js
  src/route/chats.socket.js
  src/route/docs/rooms.md
  src/route/docs/rooms.v2.md
  src/route/rooms.v2.js
  src/service/chats.js
  src/service/rooms.js
  src/service/rooms.v2.js
  src/service/users.js
Labels: rooms router, 🖥 working

#116 [Bug] auth.replace 유저 생성 안됨
  src/route/auth.replace.js
Labels: 😱bug, authentication

#117 #114 [bug] Express & Socket.io sessions are not synchronized automatically
  src/route/chats.socket.js
  src/service/rooms.v2.js
Labels: 😱bug, chatting

#120 Add: update settlement schema and settlement APIs
  src/db/mongo.js
  src/route/chats.socket.js
  src/route/docs/rooms.v2.md
  src/route/rooms.v2.js
  src/service/rooms.js
  src/service/rooms.v2.js
Labels: documentation, rooms router

#123 #106 remove unused APIs
  app.js
  src/route/docs/rooms.v2.md
  src/route/rooms.js
  src/route/rooms.v2.js
  src/route/static.js
  src/route/users.js
  src/service/rooms.js
  src/service/rooms.v2.js
  src/service/static.js
  src/service/users.js
Labels: users router, rooms router, static router, 🖥 working

#129 #128 bug sso ku std no not loaded
  src/service/auth.js
Labels: 😱bug, authentication
