Repository sparcs-kaist/taxi-back, pull requests merged in 2023-05, with the labels that each got.

#290 Fix: add populate in emitchatEvent
  src/modules/socket.js
Labels: 😱 bug, chatting

#291 #263-채팅-socket-구조-개편
  src/modules/auths/login.js
  src/modules/socket.js
  src/services/chats.js
  src/services/rooms.js
Labels: chatting

#296 #265 방 이름 정규식에서 '~'를 비롯한 특수문자 허용
  src/modules/patterns.js
Labels: ⚒ enhancement

#298 #187.2 IOS 앱에 FCM 알림 메시지 보내기
  src/modules/fcm.js
Labels: notifications router

#299 #187.3 IOS 앱에 FCM 알림 메시지 보내기
  src/modules/fcm.js
Labels: 😱 bug, notifications router
