Repository sparcs-kaist/taxi-back, pull requests merged in 2023-09, with the labels that each got.

#331 #329 `/users/editAccount` API에서 빈 문자열 입력 허용
  src/modules/patterns.js
Labels: users router

#306 #267 출발전 알림 보내기
  app.js
  package.json
  pnpm-lock.yaml
  src/modules/socket.js
  src/modules/stores/mongo.js
  src/schedules/index.js
  src/schedules/notifyAfterArrival.js
  src/schedules/notifyBeforeDepart.js
  src/services/auth.js
  src/services/chats.js
Labels: ⚒ enhancement, 🖥 working

#343 DB 시작 코드 분리
  app.js
  src/modules/stores/mongo.js
Labels: ⚒ enhancement

#344 #334 event/23-chuseok 초반 구성
  .gitignore
  app.js
  loadenv.js
  src/lottery/index.js
  src/lottery/modules/stores/mongo.js
  src/lottery/routes/transactions.js
  src/lottery/services/transactions.js
  src/middlewares/auth.js
  test/utils.js
Labels: event/23-chuseok router

#347 #336 `/event/23-chuseok/items/list` API 생성
  src/lottery/index.js
  src/lottery/routes/docs/index.js
  src/lottery/routes/docs/items.js
  src/lottery/routes/docs/swaggerDocs.js
  src/lottery/routes/items.js
  src/lottery/services/items.js
  src/routes/docs/logininfo.js
Labels: event/23-chuseok router

#349 #348 `/event/23-chuseok/admin` 페이지 생성
  app.js
  src/lottery/index.js
  src/lottery/routes/admin.js
Labels: event/23-chuseok router

#346 #338 /event/23-chuseok/global-state 와 /event/23-chuseok/balance API 생성
  src/lottery/index.js
  src/lottery/routes/docs/globalState.js
  src/lottery/routes/docs/swaggerDocs.js
  src/lottery/routes/globalState.js
  src/lottery/services/globalState.js
Labels: event/23-chuseok router

#351 #350 `/events/2023fall/items/list`에서 itemType 반환
  src/lottery/routes/docs/items.js
  src/lottery/services/items.js
Labels: event/23-chuseok router

#352 #339 /event/23-chuseok/items/purchase/:itemId 와 /event/23-chuseok/items/random_box API 생성
  src/lottery/modules/credit.js
  src/lottery/routes/docs/items.js
  src/lottery/routes/items.js
  src/lottery/services/globalState.js
  src/lottery/services/items.js
Labels: event/23-chuseok router

#355 #354 2개의 admin 페이지를 하나로 병합
  src/lottery/index.js
  src/lottery/routes/admin.js
  src/routes/admin.js
Labels: admin router, event/23-chuseok router

#356 #340 `/event/23-chuseok/admin/credit_transfer` 와 `/event/23-chuseok/admin/credit_withdraw` API 생성
  src/lottery/index.js
  src/lottery/modules/admin.js
  src/lottery/modules/credit.js
  src/lottery/services/items.js
  src/modules/adminResource.js
  src/routes/admin.js
Labels: admin router, event/23-chuseok router

#357 #337 /event/23-chuseok/transactions API 생성
  src/lottery/modules/admin.js
  src/lottery/modules/populates/transactions.js
  src/lottery/modules/stores/mongo.js
  src/lottery/routes/docs/swaggerDocs.js
  src/lottery/routes/docs/transactions.js
  src/lottery/services/globalState.js
  src/lottery/services/items.js
  src/lottery/services/transactions.js
Labels: documentation, event/23-chuseok router

#359 #358 /events/2023fall/global-state API에서 이벤트 목록을 반환하도록 개선
  src/lottery/modules/admin.js
  src/lottery/modules/credit.js
  src/lottery/modules/stores/mongo.js
  src/lottery/routes/docs/globalState.js
  src/lottery/services/globalState.js
  src/lottery/services/items.js
  src/lottery/services/transactions.js
Labels: event/23-chuseok router

#363 #362 Event에 imageUrl 필드 추가
  src/lottery/modules/stores/mongo.js
  src/lottery/routes/docs/eventsSchema.js
  src/lottery/routes/docs/globalState.js
  src/lottery/routes/docs/items.js
  src/lottery/routes/docs/itemsSchema.js
  src/lottery/routes/docs/swaggerDocs.js
  src/lottery/routes/docs/transactions.js
Labels: event/23-chuseok router

#367 #366 응모권 리더보드 API 추가
  src/lottery/index.js
  src/lottery/modules/stores/mongo.js
  src/lottery/routes/docs/publicNotice.js
  src/lottery/routes/docs/swaggerDocs.js
  src/lottery/routes/publicNotice.js
  src/lottery/services/globalState.js
  src/lottery/services/items.js
  src/lottery/services/publicNotice.js
Labels: event/23-chuseok router

#364 #341 2023 가을학기 추석 홍보 이벤트 위한 transactions
  src/lottery/index.js
  src/lottery/modules/admin.js
  src/lottery/modules/contracts/2023fall.js
  src/lottery/modules/credit.js
  src/lottery/modules/populates/transactions.js
  src/lottery/modules/quests.js
  src/lottery/modules/stores/mongo.js
  src/lottery/routes/docs/eventsSchema.js
  src/lottery/routes/docs/globalState.js
  src/lottery/routes/docs/swaggerDocs.js
  src/lottery/routes/docs/transactions.js
  src/lottery/services/globalState.js
  src/lottery/services/items.js
  src/lottery/services/transactions.js
  src/modules/adminResource.js
  src/services/auth.js
  src/services/auth.mobile.js
  src/services/rooms.js
  src/services/users.js
Labels: event/23-chuseok router

#373 #372 이벤트 참여 동의 여부 확인
  src/lottery/modules/contracts/2023fall.js
  src/lottery/modules/quests.js
  src/lottery/routes/docs/globalState.js
  src/lottery/routes/docs/itemsSchema.js
  src/lottery/routes/globalState.js
  src/lottery/routes/items.js
  src/lottery/services/globalState.js
  src/lottery/services/items.js
  src/services/notifications.js
  src/services/rooms.js
  src/services/users.js
Labels: event/23-chuseok router

#370 #361 상점 공지 문구 API #360 이벤트 달성완료 API
  src/lottery/index.js
  src/lottery/modules/contracts/2023fall.js
  src/lottery/modules/populates/transactions.js
  src/lottery/modules/stores/mongo.js
  src/lottery/routes/docs/publicNotice.js
  src/lottery/routes/docs/quests.js
  src/lottery/routes/docs/swaggerDocs.js
  src/lottery/routes/publicNotice.js
  src/lottery/routes/quests.js
  src/lottery/services/items.js
  src/lottery/services/publicNotice.js
  src/lottery/services/quests.js
Labels: event/23-chuseok router

#379 #377 이벤트 참여 동의시 전화번호 수집하여 저장
  src/lottery/routes/docs/globalState.js
  src/lottery/routes/docs/globalStateSchema.js
  src/lottery/routes/docs/publicNotice.js
  src/lottery/routes/docs/quests.js
  src/lottery/routes/docs/swaggerDocs.js
  src/lottery/routes/globalState.js
  src/lottery/services/globalState.js
  src/modules/stores/mongo.js
Labels: event/23-chuseok router

#380 #341.2 이벤트 퀘스트 이름 및 설명 수정
  src/lottery/modules/contracts/2023fall.js
Labels: event/23-chuseok router

#382 #381 eventConfig 활성화
  loadenv.js
  src/lottery/modules/contracts/2023fall.js
  src/services/rooms.js
Labels: event/23-chuseok router

#384 #383 `/global-state/create` Endpoint에 이벤트 기간에만 접근 가능하도록 변경
  src/lottery/middlewares/timestampValidator.js
  src/lottery/routes/docs/quests.js
  src/lottery/routes/globalState.js
  src/lottery/routes/items.js
  src/lottery/routes/quests.js
  src/lottery/services/globalState.js
  src/lottery/services/items.js
  src/lottery/services/publicNotice.js
Labels: 😱 bug, event/23-chuseok router

#388 #387 아이템 관련 API 개선
  src/lottery/modules/quests.js
  src/lottery/routes/docs/itemsSchema.js
  src/lottery/services/items.js
  src/lottery/services/publicNotice.js
  src/lottery/services/transactions.js
Labels: event/23-chuseok router

#390 #389 adminJS에 아이템 재고 추가 Action 추가
  src/lottery/index.js
  src/lottery/modules/items.js
  src/modules/adminResource.js
Labels: admin router, event/23-chuseok router

#392 #391 방 공유 퀘스트 완료 API 추가
  src/lottery/modules/contracts/2023fall.js
  src/lottery/modules/populates/transactions.js
  src/lottery/modules/quests.js
  src/lottery/modules/stores/mongo.js
  src/lottery/routes/docs/globalState.js
  src/lottery/routes/docs/items.js
  src/lottery/routes/docs/itemsSchema.js
  src/lottery/routes/docs/quests.js
  src/lottery/routes/docs/questsSchema.js
  src/lottery/routes/docs/swaggerDocs.js
  src/lottery/routes/quests.js
  src/lottery/services/items.js
  src/lottery/services/quests.js
Labels: event/23-chuseok router

#385 #378 public notice API 개선
  src/lottery/services/publicNotice.js
Labels: event/23-chuseok router

#394 #393 테스트 과정 중 발생한 버그 수정
  src/lottery/routes/docs/publicNotice.js
  src/lottery/services/globalState.js
  src/lottery/services/publicNotice.js
Labels: 😱 bug, event/23-chuseok router

#397 [Bug] trust proxy 설정
  app.js
  src/middlewares/limitRate.js
Labels: 😱 bug, event/23-chuseok router

#305 #270 안 읽은 메세지 확인
  src/modules/auths/login.js
  src/modules/populates/rooms.js
  src/modules/socket.js
  src/modules/stores/mongo.js
  src/routes/chats.js
  src/services/chats.js
Labels: chatting

#401 #400 정산 및 송금 요청 관련 퀘스트 달성 조건 변경
  src/lottery/modules/contracts/2023fall.js
Labels: 😱 bug, event/23-chuseok router

#408 #407 리더보드 확률 모델 정확도 개선
  src/lottery/services/publicNotice.js
Labels: 😱 bug, event/23-chuseok router

#410 #399.1 `logininfo` API에 `phoneNumber` 추가
  src/routes/docs/logininfo.js
  src/services/logininfo.js
Labels: logininfo router
