Repository sparcs-kaist/taxi-back, pull requests merged in 2023-11, with the labels that each got.

#262 #135.5 auth API에 swagger 적용
  src/routes/docs/auth.js
  src/routes/docs/auth.md
  src/routes/docs/locations.js
  src/routes/docs/logininfo.js
  src/routes/docs/reports.js
  src/routes/docs/swaggerDocs.js
Labels: documentation

#427 #426 [Bug] Swagger api 테스트가 작동하지 않음
  src/routes/docs/swaggerDocs.js
Labels: 😱 bug

#429 #188 로그인 만료 시간이 너무 짧음 - cookie의 expiry 추가, #428 Redis 연결 실패 시 재시도 추가
  app.js
  loadenv.js
  src/middlewares/session.js
  src/modules/auths/login.js
  src/modules/stores/sessionStore.js
Labels: 😱 bug, authentication

#434 #433 [Bug] trust proxy 값이 잘못 설정됨
  app.js
Labels: 😱 bug, authentication
