Repository sparcs-kaist/taxi-back, pull requests merged in 2023-04, with the labels that each got.

#259 #176 알림 세부 설정
  package-lock.json
  package.json
  src/routes/auth.js
  src/routes/auth.replace.js
  src/routes/notifications.js
  src/services/auth.js
  src/services/auth.replace.js
  src/services/notifications.js
Labels: notifications router

#260 #176.2 fcm 모듈 버그
  src/modules/fcm.js
Labels: notifications router

#261 Fix: [Bug] loadenv `TEST_ACCOUNTS` 오타 수정
  loadenv.js
Labels: 😱 bug, authentication

#271 #264 로그인, 로그아웃 API 에 입력 주소로 redirect 기능 추가
  src/routes/auth.js
  src/routes/auth.replace.js
  src/routes/rooms.js
  src/services/auth.js
  src/services/auth.replace.js
  src/services/rooms.js
Labels: authentication

#279 #278 logininfo test 관련 수정
  test/logininfo.js
Labels: testcase

#281 #280 로그인을 요구하지 않는 방 정보 반환 API 개발
  .eslintrc.js
  src/modules/populates/rooms.js
  src/routes/docs/rooms.md
  src/routes/rooms.js
  src/services/rooms.js
  test/rooms.js
Labels: rooms router

#282 #188.2 로그인 만료 기간을 (다시) 2주로 연장
  src/modules/auths/login.js
Labels: authentication

#277 #265 방 이름 정규식에서 '~'를 비롯한 특수문자 허용
  app.js
  src/modules/patterns.js
Labels: ⚒ enhancement, 🖥 working

#284 #265 방 이름 정규식에서 '~'를 비롯한 특수문자 허용
  src/modules/patterns.js
Labels: 😱 bug

#268 #263 채팅 socket 구조 개편
  app.js
  package-lock.json
  package.json
  src/middlewares/session.js
  src/modules/auths/login.js
  src/modules/patterns.js
  src/modules/socket.js
  src/routes/chats.js
  src/services/auth.js
  src/services/auth.mobile.js
  src/services/auth.replace.js
  src/services/chats.js
  src/services/rooms.js
  src/services/socket.chats.js
Labels: chatting
