Repository sparcs-kaist/taxi-back, pull requests merged in 2023-08, with the labels that each got.

#304 #303 introduce aws ses
  loadenv.js
  package-lock.json
  package.json
  src/modules/slackNotification.js
  src/modules/socket.js
  src/modules/stores/aws.js
  src/modules/stores/mongo.js
  src/routes/docs/reportsSchema.js
  src/services/auth.replace.js
  src/services/chats.js
  src/services/reports.js
  src/services/users.js
  src/views/emailNoSettlementPage.js
  src/views/emailPage.js
  src/views/loginReplacePage.js
  test/reports.js
  test/utils.js
Labels: reports router

#321 #320 `/locations` API에 위도, 경도 추가
  src/modules/stores/mongo.js
Labels: locations router

#319 #316 `FRONT_URL` 환경변수 제거
  .env.example
  README.md
  app.js
  loadenv.js
  src/middlewares/authAdmin.js
  src/middlewares/cors.js
  src/middlewares/information.js
  src/modules/socket.js
  src/services/auth.js
  src/services/auth.replace.js
  src/services/reports.js
  src/views/emailNoSettlementPage.js
  src/views/loginReplacePage.js
  test/auth.replace.js
Labels: ⚒ enhancement

#328 #324 [Bug] joinus 함수에서 req 인자가 누락되어 회원가입 불가, #325 [Bug] SPARCS SSO callback 핸들러에 임의로 접근한 경우 TypeError 발생
  src/services/auth.js
  src/services/auth.replace.js
Labels: 😱 bug

#327 #326 Global error handler 추가
  app.js
  src/middlewares/errorHandler.js
Labels: ⚒ enhancement
