Repository sparcs-kaist/taxi-back, pull requests merged in 2023-02, with the labels that each got.

#219 #177 [Bug] 카이스트 구성원이 아닌 경우 로그인 불가
  src/service/auth.js
Labels: 😱 bug, authentication

#202 #185 users.js 테스트 케이스 제작
  package-lock.json
  package.json
  src/service/users.js
  test/rooms.js
  test/users.js
  test/utils.js
Labels: 🖥 working, testcase

#220 #135.2 Introduce Swagger
  app.js
  package-lock.json
  package.json
  security.js
  src/route/docs.js
  src/route/docs/logininfo.md
  src/route/logininfo.js
Labels: documentation

#224 #223 reports.js 테스트 케이스 제작
  test/reports.js
  test/rooms.js
  test/users.js
Labels: testcase

#226 #225 httpmock으로 리팩토링
  test/auth.replace.js
  test/locations.js
  test/logininfo.js
  test/reports.js
  test/rooms.js
  test/users.js
  test/utils.js
Labels: testcase
