Repository sparcs-kaist/taxi-back, pull requests merged in 2024-09, with the labels that each got.

#530 #520 ban 여부에 따른 서비스 이용 제한
  src/middlewares/ban.js
  src/modules/ban.js
  src/modules/stores/mongo.js
  src/routes/docs/rooms.js
  src/routes/docs/users.js
  src/routes/rooms.js
  src/routes/users.js
  src/services/users.js
Labels: ⚒ enhancement

#545 #540 24 추석 이벤트 관련 마이너 변경사항
  src/lottery/modules/contracts.js
  src/lottery/modules/quests.js
  src/lottery/routes/docs/globalState.js
  src/lottery/routes/docs/items.js
  src/lottery/services/items.js
Labels: event/24-chuseok

#548 #547 [Bug] FCM 푸시 알림이 수신되지 않는 버그
  package.json
  pnpm-lock.yaml
  src/modules/fcm.js
Labels: 😱 bug

#551 #550 [Bug] FCM 푸시 알림이 수신되지 않는 버그 2
  src/modules/fcm.js
Labels: 😱 bug
