Repository sparcs-kaist/taxi-back, pull requests merged in 2024-03, with the labels that each got.

#480 #479 [Bug] 참여자가 1명인 방에 대해서도 어뷰징 감지 스크립트가 반응하는 버그
  src/lottery/schedules/detectAbusingUsers.js
Labels: 😱 bug, event/24-spring

#482 세션 만료 시 Socket.io 연결 차단
  src/modules/socket.js
Labels: 😱 bug

#462 #461 메일 전송 SMTP으로 변경
  loadenv.js
  package.json
  pnpm-lock.yaml
  src/modules/email.js
  src/modules/stores/aws.js
  src/services/reports.js
Labels: ⚒ enhancement

#484 #471 introduce zod
  package.json
  pnpm-lock.yaml
  src/lottery/routes/docs/globalStateSchema.js
  src/lottery/routes/docs/inviteSchema.js
  src/lottery/routes/docs/questsSchema.js
  src/lottery/routes/docs/schemas/globalStateSchema.js
  src/lottery/routes/docs/schemas/inviteSchema.js
  src/lottery/routes/docs/schemas/itemsSchema.js
  src/lottery/routes/docs/schemas/questsSchema.js
  src/lottery/routes/docs/swaggerDocs.js
  src/lottery/routes/globalState.js
  src/lottery/routes/invite.js
  src/lottery/routes/items.js
  src/lottery/routes/quests.js
  src/middlewares/zod.js
  src/modules/patterns.js
  src/routes/docs/chats.js
  src/routes/docs/logininfo.js
  src/routes/docs/reports.js
  src/routes/docs/rooms.js
  src/routes/docs/schemas/reportsSchema.js
  src/routes/docs/schemas/roomsSchema.js
  src/routes/docs/swaggerDocs.js
  src/routes/docs/utils.js
  src/routes/reports.js
Labels: documentation

#500 #499 [Bug] 메일 전송 안됨
  src/modules/email.js
Labels: 😱 bug

#488 #485 노쇼 대응 이메일 템플릿 추가 및 자동화
  app.js
  src/modules/email.js
  src/modules/fcm.js
  src/modules/stores/mongo.js
  src/services/reports.js
  src/views/emailNoSettlementPage.js
  src/views/emailPage.js
  src/views/reportEmailPage.js
Labels: reports router

#506 #505 새터반 택시대제전 코드 비활성화
  loadenv.js
Labels: event/24-spring
