Repository sparcs-kaist/taxi-back, pull requests merged in 2024-02, with the labels that each got.

#445 #135.8 rooms API에 swagger 적용
  src/routes/docs/rooms.js
  src/routes/docs/rooms.md
  src/routes/docs/roomsSchema.js
  src/routes/docs/swaggerDocs.js
  src/routes/docs/utils.js
  src/services/rooms.js
Labels: documentation

#448 #447 startSocketServer 함수 리팩토링
  src/modules/socket.js
Labels: ⚒ enhancement, chatting

#459 #441 방 생성 시각의 유효성을 검사하지 않는 버그
  src/routes/docs/rooms.js
  src/services/rooms.js
Labels: 😱 bug, rooms router

#465 #456 퀘스트 시스템 활성화
  app.js
  loadenv.js
  src/lottery/index.js
  src/lottery/middlewares/timestampValidator.js
  src/lottery/modules/contracts.js
  src/lottery/modules/quests.js
  src/lottery/modules/stores/mongo.js
  src/lottery/routes/docs/globalState.js
  src/lottery/routes/docs/globalStateSchema.js
  src/lottery/routes/docs/items.js
  src/lottery/routes/docs/publicNotice.js
  src/lottery/routes/docs/quests.js
  src/lottery/routes/docs/questsSchema.js
  src/lottery/routes/docs/swaggerDocs.js
  src/lottery/routes/docs/transactions.js
  src/lottery/routes/items.js
  src/lottery/routes/publicNotice.js
  src/lottery/routes/quests.js
  src/lottery/routes/transactions.js
  src/lottery/services/globalState.js
  src/lottery/services/items.js
  src/lottery/services/publicNotice.js
  src/lottery/services/quests.js
  src/lottery/services/transactions.js
  src/routes/admin.js
Labels: event/24-spring

#470 #457 추천인 시스템 구현
  src/lottery/index.js
  src/lottery/modules/contracts.js
  src/lottery/modules/quests.js
  src/lottery/modules/stores/mongo.js
  src/lottery/routes/docs/invite.js
  src/lottery/routes/docs/inviteSchema.js
  src/lottery/routes/docs/quests.js
  src/lottery/routes/docs/questsSchema.js
  src/lottery/routes/docs/swaggerDocs.js
  src/lottery/routes/invite.js
  src/lottery/services/globalState.js
  src/lottery/services/invite.js
Labels: event/24-spring

#472 #467 어뷰징 대응 자동화
  src/lottery/index.js
  src/lottery/modules/slackNotification.js
  src/lottery/schedules/detectAbusingUsers.js
  src/lottery/schedules/index.js
  src/modules/slackNotification.js
  src/routes/rooms.js
  src/services/reports.js
  src/services/rooms.js
Labels: event/24-spring

#475 #474 추천인 퀘스트 설명 업데이트
  src/lottery/modules/contracts.js
  src/lottery/services/globalState.js
Labels: event/24-spring

#477 #476 안티 어뷰징 시스템 개선
  src/modules/slackNotification.js
  src/services/rooms.js
Labels: event/24-spring
