Repository sparcs-kaist/taxi-back, pull requests merged in 2024-05, with the labels that each got.

#518 #517 미정산 시 방 생성/참여 차단
  src/routes/docs/rooms.js
  src/services/rooms.js
Labels: rooms router

#515 #514 랜덤 이메일 업데이트
  src/services/auth.js
Labels: 😱 bug

#519 #516 blockedlist
  src/modules/stores/mongo.js
  src/routes/admin.js
  src/routes/docs/users.js
  src/routes/users.js
  src/services/users.js
Labels: ⚒ enhancement
